name: publish-dev

on: 
  workflow_dispatch:
  push:
    branches:
      - 'rc/*/*/*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: publish dev
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run publish-dev
